# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-14 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos', models.FloatField()),
                ('porcentaje', models.FloatField()),
                ('ingresos_neto', models.FloatField()),
            ],
        ),
    ]
