# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-14 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=50)),
                ('universidad', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('año_egreso', models.IntegerField()),
            ],
        ),
    ]
